import math
from workflow_cases import workflow_cases
from pathlib import Path

def sketch(id,primitives,plane='Front',**kw):
    return dict(type='ProfileSketch',id=id,name=id,plane=plane,primitives=primitives,**kw)
def boss(id,sketch_id,depth,**kw):
    return dict(type='ExtrudeBoss',id=id,name=id,sketch_id=sketch_id,depth_mm=depth,**({'end_condition':'Blind'}|kw))
def feature(id,kind,**kw):
    return dict(type='NativeFeature',id=id,name=id,feature=dict(kind=kind,**kw))
def rect(w,h,x=0,y=0):
    return dict(type='CenteredRectangle',center_xmm=x,center_ymm=y,width_mm=w,height_mm=h)
def circle(d,role='Outer',x=0,y=0):
    return dict(type='Circle',role=role,center_xmm=x,center_ymm=y,diameter_mm=d)
def draft(name,ops,**kw):
    return dict(name=name,operations=ops,**({'source_text':'Native modeling regression: '+name}|kw))

cases={
 'tube_chamfer':draft('tube_chamfer',[
    sketch('tube_profile',[circle(60),circle(30,'Inner')]),boss('tube','tube_profile',100),
    feature('bore_chamfer','Chamfer',distance_mm=5,angle_degrees=45,selections=[dict(kind='Edge',feature_id='tube',geometry='Circle',radius_mm=15,position_mm=dict(x=15,y=0,z=100))])
 ],expected_volume_mm3=(67500-1250/3)*math.pi,volume_tolerance_percent=.01),
 'box_fillet':draft('box_fillet',[
    sketch('base',[rect(40,30)]),boss('block','base',10),
    feature('corners','Fillet',radius_mm=2,selections=[dict(kind='Edge',feature_id='block',geometry='Line',direction=dict(x=0,y=0,z=1),all_matches=True)])
 ],expected_volume_mm3=(1200-4*(4-math.pi))*10,volume_tolerance_percent=.01),
 'inclined_plane':draft('inclined_plane',[
    sketch('inclined',[rect(20,10)],frame=dict(origin_mm=dict(x=0,y=0,z=10),x_direction=dict(x=1,y=0,z=0),normal=dict(x=0,y=-.5,z=math.sqrt(3)/2))),
    boss('inclined_block','inclined',5)
 ],expected_volume_mm3=1000,volume_tolerance_percent=.01),
 'revolved_ring':draft('revolved_ring',[
    feature('axis','ReferenceAxis',axis_start_mm=dict(x=0,y=-20,z=0),axis_end_mm=dict(x=0,y=20,z=0)),
    sketch('section',[rect(5,20,x=12.5)]),
    feature('revolve','RevolveBoss',sketch_id='section',axis_id='axis',angle_degrees=360)
 ],expected_volume_mm3=math.pi*(225-100)*20,volume_tolerance_percent=.01,expected_bounding_box_mm=dict(x=30,y=20,z=30))
}

cases.update({
 'weldment_bar':draft('weldment_bar',[
    sketch('path',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=100,ymm=0))])]),
    feature('bar','WeldmentMember',path_sketch_id='path',profile_path=r'C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2025\weldment profiles\GB\square-rods.sldlfp',profile_configuration='SQUARE BAR 10')
 ],expected_volume_mm3=10000,volume_tolerance_percent=.01),
 'weldment_trim':draft('weldment_trim',[
    sketch('path_a',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=80,ymm=0))])]),
    feature('bar_a','WeldmentMember',path_sketch_id='path_a',profile_path=r'C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2025\weldment profiles\GB\square-rods.sldlfp',profile_configuration='SQUARE BAR 10'),
    sketch('path_b',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=80,ymm=-30),end=dict(xmm=80,ymm=30))])]),
    feature('bar_b','WeldmentMember',path_sketch_id='path_b',profile_path=r'C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2025\weldment profiles\GB\square-rods.sldlfp',profile_configuration='SQUARE BAR 10'),
    feature('trim','TrimWeldment',selections=[dict(kind='Body',feature_id='bar_a'),dict(kind='Body',feature_id='bar_b',selection_mark=2)])
 ],expected_solid_body_count=2,expected_volume_mm3=13500,volume_tolerance_percent=.01),
 'face_fillet':draft('face_fillet',[
    sketch('base',[rect(40,30)]),boss('block','base',10),
    feature('fillet','Fillet',radius_mm=2,selections=[dict(kind='Face',feature_id='block',position_mm=dict(x=20,y=0,z=5),selection_mark=2),dict(kind='Face',feature_id='block',position_mm=dict(x=0,y=15,z=5),selection_mark=4)])
 ],expected_volume_mm3=12000-(4-math.pi)*10,volume_tolerance_percent=.01),
 'unequal_chamfer':draft('unequal_chamfer',[
    sketch('base',[rect(40,30)]),boss('block','base',10),
    feature('chamfer','Chamfer',chamfer_mode='TwoDistances',distance_mm=2,second_distance_mm=3,selections=[dict(kind='Edge',feature_id='block',position_mm=dict(x=20,y=15,z=5))])
 ],expected_volume_mm3=11970,volume_tolerance_percent=.01),
 'draft_block':draft('draft_block',[
    sketch('base',[rect(40,30)]),boss('block','base',20),
    feature('draft','Draft',angle_degrees=5,selections=[dict(kind='Face',feature_id='block',position_mm=dict(x=0,y=0,z=0),selection_mark=1),dict(kind='Face',feature_id='block',position_mm=dict(x=20,y=0,z=10),selection_mark=2)])
 ]),
 'move_rotate_copy':draft('move_rotate_copy',[
    sketch('base',[rect(20,10)]),boss('block','base',5),
    feature('moved','MoveBody',translation_mm=dict(x=30,y=0,z=0),rotation_degrees=dict(x=0,y=0,z=90),copy=True,count=1,selections=[dict(kind='Body',feature_id='block')])
 ],expected_solid_body_count=2,expected_volume_mm3=2000,volume_tolerance_percent=.01,expected_bounding_box_mm=dict(x=20,y=45,z=5),expected_center_of_mass_mm=dict(x=0,y=15,z=2.5)),
 'move_rotate_xyz':draft('move_rotate_xyz',[
    sketch('base',[rect(20,10)]),boss('block','base',5),
    feature('rotated','MoveBody',rotation_degrees=dict(x=90,y=90,z=90),selections=[dict(kind='Body',feature_id='block')])
 ],expected_volume_mm3=1000,volume_tolerance_percent=.01,expected_bounding_box_mm=dict(x=5,y=10,z=20),expected_center_of_mass_mm=dict(x=2.5,y=0,z=0)),
 'sweep_guide':draft('sweep_guide',[
    sketch('profile',[circle(10)]),
    sketch('path',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=0,ymm=40))])],plane='Top'),
    sketch('guide',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=5,ymm=0),end=dict(xmm=5,ymm=40))])],plane='Top'),
    feature('sweep','SweepBoss',sketch_id='profile',path_sketch_id='path',guide_ids=['guide'])
 ],expected_volume_mm3=1000*math.pi,volume_tolerance_percent=.1),
 'revolve_cut':draft('revolve_cut',[
    sketch('base',[rect(40,30)]),boss('block','base',10),
    feature('axis','ReferenceAxis',axis_start_mm=dict(x=0,y=0,z=0),axis_end_mm=dict(x=0,y=0,z=20)),
    sketch('section',[rect(5,10,x=7.5,y=5)],frame=dict(normal=dict(x=0,y=-1,z=0))),
    feature('groove','RevolveCut',sketch_id='section',axis_id='axis')
 ],expected_solid_body_count=2,expected_volume_mm3=12000-750*math.pi,volume_tolerance_percent=.01),
 'thin_revolve':draft('thin_revolve',[
    feature('axis','ReferenceAxis',axis_start_mm=dict(x=0,y=-10,z=0),axis_end_mm=dict(x=0,y=30,z=0)),
    sketch('section',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=10,ymm=0),end=dict(xmm=10,ymm=20))])]),
    feature('tube','RevolveBoss',sketch_id='section',axis_id='axis',thickness_mm=2)
 ]),
 'sketch_pattern':draft('sketch_pattern',[
    sketch('base',[rect(80,40)]),boss('plate','base',10),
    feature('hole','Hole',diameter_mm=6,hole_centers=[dict(xmm=-20,ymm=0)]),
    sketch('locations',[dict(type='Points',points=[dict(xmm=-20,ymm=0),dict(xmm=0,ymm=0),dict(xmm=20,ymm=0)])]),
    feature('pattern','SketchPattern',sketch_id='locations',selections=[dict(kind='Feature',feature_id='hole',selection_mark=4)])
 ],expected_volume_mm3=32000-3*90*math.pi,volume_tolerance_percent=.01),
 'ellipse':draft('ellipse',[
    sketch('profile',[dict(type='Ellipse',center_xmm=0,center_ymm=0,width_mm=40,height_mm=20)]),boss('oval','profile',5)
 # Native ellipse integration differs from analytic pi*a*b by approximately 0.0244% in SW 2025, including its highest mass-property accuracy.
 ],expected_volume_mm3=1000*math.pi,volume_tolerance_percent=.05,expected_bounding_box_mm=dict(x=40,y=20,z=5)),
 'concentric_constraint':draft('concentric_constraint',[
    sketch('profile',[circle(20),circle(10,'Inner',x=1)],constraints=[dict(kind='Concentric',entities=[dict(primitive_index=0),dict(primitive_index=1)])],
        dimensions=[dict(name='OuterDiameter',kind='Diameter',value=20,entities=[dict(primitive_index=0)]),dict(name='InnerDiameter',kind='Diameter',value=10,entities=[dict(primitive_index=1)])]),boss('ring','profile',10)
 ],expected_volume_mm3=750*math.pi,volume_tolerance_percent=.01),
 'equal_constraint':draft('equal_constraint',[
    sketch('profile',[circle(10,x=-10),circle(10,x=10)],constraints=[dict(kind='Equal',entities=[dict(primitive_index=0),dict(primitive_index=1)])]),boss('pins','profile',10)
 ],expected_solid_body_count=2,expected_volume_mm3=500*math.pi,volume_tolerance_percent=.01),
 'tangent_constraint':draft('tangent_constraint',[
    sketch('profile',[circle(20),dict(type='OpenCurve',construction=True,curves=[dict(type='Line',start=dict(xmm=-15,ymm=10),end=dict(xmm=15,ymm=10))])],
        constraints=[dict(kind='Tangent',entities=[dict(primitive_index=0),dict(primitive_index=1)])]),boss('pin','profile',10)
 ],expected_volume_mm3=1000*math.pi,volume_tolerance_percent=.01),
 'symmetric_constraint':draft('symmetric_constraint',[
    sketch('profile',[circle(10,x=-10),circle(10,x=10),dict(type='OpenCurve',construction=True,curves=[dict(type='Line',start=dict(xmm=0,ymm=-20),end=dict(xmm=0,ymm=20))])],
        constraints=[dict(kind='Symmetric',entities=[dict(primitive_index=0,part='CenterPoint'),dict(primitive_index=1,part='CenterPoint'),dict(primitive_index=2)])]),boss('pins','profile',10)
 ],expected_solid_body_count=2,expected_volume_mm3=500*math.pi,volume_tolerance_percent=.01),
 'suppress_restore':draft('suppress_restore',[
    sketch('base',[rect(40,30)]),boss('block','base',10),feature('hole','Hole',diameter_mm=6,hole_centers=[dict(xmm=0,ymm=0)]),
    feature('suppress','Suppress',selections=[dict(kind='Feature',feature_id='hole')]),feature('restore','Restore',selections=[dict(kind='Feature',feature_id='hole')])
 ],expected_volume_mm3=12000-90*math.pi,volume_tolerance_percent=.01),
 'up_to_next':draft('up_to_next',[
    sketch('top',[rect(40,30)],frame=dict(origin_mm=dict(x=0,y=0,z=20))),boss('plate','top',5),
    sketch('bottom',[circle(10)]),boss('rod','bottom',50,end_condition='UpToNext')
 ],expected_volume_mm3=6000+500*math.pi,volume_tolerance_percent=.01),
 'up_to_surface':draft('up_to_surface',[
    sketch('top',[rect(40,30)],frame=dict(origin_mm=dict(x=0,y=0,z=20))),boss('plate','top',5),
    sketch('bottom',[circle(10)]),boss('rod','bottom',50,end_condition='UpToSurface',end_reference=dict(support_operation_id='plate',pick_xmm=0,pick_ymm=0,pick_zmm=20))
 ],expected_volume_mm3=6000+500*math.pi,volume_tolerance_percent=.01),
 'surface_loft':draft('surface_loft',[
    sketch('bottom',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=-20,ymm=0),end=dict(xmm=20,ymm=0))])]),
    sketch('top',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=-20,ymm=0),end=dict(xmm=20,ymm=0))])],frame=dict(origin_mm=dict(x=0,y=0,z=20))),
    feature('surface','SurfaceLoft',profile_ids=['bottom','top'])
 ],expected_solid_body_count=0,expected_surface_body_count=1,expected_bounding_box_mm=dict(x=40,y=0,z=20)),
 'spline_surface':draft('spline_surface',[
    sketch('curve',[dict(type='Spline',points=[dict(xmm=-20,ymm=0),dict(xmm=-10,ymm=10),dict(xmm=10,ymm=-10),dict(xmm=20,ymm=0)])]),
    feature('surface','SurfaceExtrude',sketch_id='curve',depth_mm=20)
 ],expected_solid_body_count=0,expected_surface_body_count=1),
 'sketch_offset':draft('sketch_offset',[
    sketch('profile',[circle(20)],edits=[dict(kind='Offset',offset_mm=2,entities=[dict(primitive_index=0)])]),boss('ring','profile',10)
 ],expected_volume_mm3=440*math.pi,volume_tolerance_percent=.01),
 'sketch_trim':draft('sketch_trim',[
    sketch('profile',[dict(type='OpenCurve',curves=[
        dict(type='Line',start=dict(xmm=-20,ymm=0),end=dict(xmm=20,ymm=0)),
        dict(type='Line',start=dict(xmm=0,ymm=-10),end=dict(xmm=0,ymm=10))])],
        edits=[dict(kind='TrimClosest',entities=[dict(primitive_index=0,segment_index=0)],pick_point=dict(xmm=10,ymm=0))]),
    feature('surface','SurfaceExtrude',sketch_id='profile',depth_mm=5)
 ],expected_solid_body_count=0,expected_surface_body_count=2,expected_bounding_box_mm=dict(x=20,y=20,z=5)),
 'body_mirror':draft('body_mirror',[
    sketch('base',[rect(10,10,x=20)]),boss('block','base',5),
    feature('plane','ReferencePlane',frame=dict(normal=dict(x=1,y=0,z=0),x_direction=dict(x=0,y=1,z=0))),
    feature('mirror','Mirror',merge=False,selections=[dict(kind='Body',feature_id='block',selection_mark=256),dict(kind='Plane',feature_id='plane',selection_mark=2)])
 ],expected_solid_body_count=2,expected_volume_mm3=1000,volume_tolerance_percent=.01,expected_bounding_box_mm=dict(x=50,y=10,z=5)),
 'surface_knit':draft('surface_knit',[
    sketch('left',[rect(20,30,x=-10)]),feature('left_surface','SurfacePlanar',sketch_id='left'),
    sketch('right',[rect(20,30,x=10)]),feature('right_surface','SurfacePlanar',sketch_id='right'),
    feature('knit','SurfaceKnit',selections=[dict(kind='Body',feature_id='left_surface'),dict(kind='Body',feature_id='right_surface')])
 ],expected_solid_body_count=0,expected_surface_body_count=1,expected_bounding_box_mm=dict(x=40,y=30,z=0)),
 'loft_guide':draft('loft_guide',[
    sketch('bottom',[circle(20)]),sketch('top',[circle(10)],frame=dict(origin_mm=dict(x=0,y=0,z=30))),
    sketch('guide',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=10,ymm=0),end=dict(xmm=5,ymm=30))])],frame=dict(normal=dict(x=0,y=-1,z=0))),
    feature('loft','LoftBoss',profile_ids=['bottom','top'],guide_ids=['guide'])
 ],expected_volume_mm3=1750*math.pi,volume_tolerance_percent=.1),
 'sheet_unflatten':draft('sheet_unflatten',[
    sketch('profile',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=20),end=dict(xmm=0,ymm=0)),dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=30,ymm=0))])]),
    feature('sheet','SheetMetalBase',sketch_id='profile',thickness_mm=2,radius_mm=2,depth_mm=40),feature('flatten','Flatten',flattened=True),feature('unflatten','Flatten',flattened=False)
 ]),
 'loft_cut':draft('loft_cut',[
    sketch('base',[rect(40,30)]),boss('block','base',20),
    sketch('bottom',[circle(10)]),sketch('top',[circle(20)],frame=dict(origin_mm=dict(x=0,y=0,z=20))),
    feature('cut','LoftCut',profile_ids=['bottom','top'])
 ],expected_volume_mm3=24000-math.pi*20/3*(25+50+100),volume_tolerance_percent=.1),
 'sweep_cut':draft('sweep_cut',[
    sketch('base',[rect(40,30)]),boss('block','base',20),
    sketch('profile',[circle(10)]),
    sketch('path',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=0,ymm=20))])],plane='Top'),
    feature('cut','SweepCut',sketch_id='profile',path_sketch_id='path')
 ],expected_volume_mm3=24000-500*math.pi,volume_tolerance_percent=.1),
 'surface_trim':draft('surface_trim',[
    sketch('outline',[rect(40,30)]),feature('surface','SurfacePlanar',sketch_id='outline'),
    feature('tool','ReferencePlane',frame=dict(normal=dict(x=1,y=0,z=0),x_direction=dict(x=0,y=1,z=0))),
    feature('trim','SurfaceTrim',selections=[dict(kind='Plane',feature_id='tool'),dict(kind='Body',feature_id='surface',position_mm=dict(x=10,y=0,z=0),selection_mark=2)])
 ],expected_solid_body_count=0,expected_surface_body_count=1,expected_bounding_box_mm=dict(x=20,y=30,z=0)),
 'edge_flange':draft('edge_flange',[
    sketch('outline',[rect(60,40)]),feature('sheet','SheetMetalBase',sketch_id='outline',thickness_mm=2,radius_mm=2),
    feature('flange','EdgeFlange',angle_degrees=90,distance_mm=20,selections=[dict(kind='Edge',feature_id='sheet',geometry='Line',position_mm=dict(x=0,y=20,z=0))])
 ]),
 'bent_sheet_flat':draft('bent_sheet_flat',[
    sketch('angle_profile',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=20),end=dict(xmm=0,ymm=0)),dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=30,ymm=0))])]),
    feature('sheet','SheetMetalBase',sketch_id='angle_profile',thickness_mm=2,radius_mm=2,depth_mm=40),feature('flatten','Flatten',flattened=True)
 ]),
 'constrained_circle':draft('constrained_circle',[
    sketch('profile',[circle(10,x=5)],constraints=[dict(kind='Fixed',entities=[dict(primitive_index=0,part='CenterPoint')])],
        dimensions=[dict(name='Diameter',kind='Diameter',value=20,entities=[dict(primitive_index=0)],label_position=dict(xmm=25,ymm=20))]),
    boss('cylinder','profile',10)
 ],expected_volume_mm3=1000*math.pi,volume_tolerance_percent=.01),
 'rib_support':draft('rib_support',[
    sketch('base_profile',[rect(40,30)]),boss('base','base_profile',5),
    sketch('wall_profile',[rect(40,5,y=-12.5)]),boss('wall','wall_profile',30),
    sketch('rib_profile',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=-10,ymm=25),end=dict(xmm=10,ymm=5))])],
        frame=dict(x_direction=dict(x=0,y=1,z=0),normal=dict(x=1,y=0,z=0))),
    feature('rib','Rib',sketch_id='rib_profile',thickness_mm=4)
 ],expected_volume_mm3=6000+40*5*25+20*20/2*4,volume_tolerance_percent=.01),
 'split_block':draft('split_block',[
    sketch('base',[rect(40,30)]),boss('block','base',10),
    feature('midplane','ReferencePlane',frame=dict(normal=dict(x=1,y=0,z=0),x_direction=dict(x=0,y=1,z=0))),
    feature('split','Split',selections=[dict(kind='Plane',feature_id='midplane')])
 ],expected_solid_body_count=2,expected_volume_mm3=12000,volume_tolerance_percent=.01),
 'subtract_blocks':draft('subtract_blocks',[
    sketch('base',[rect(30,20)]),boss('block','base',10),
    sketch('tool_profile',[rect(10,10)]),boss('tool','tool_profile',10,merge=False),
    feature('subtract','Combine',boolean_mode='Subtract',selections=[dict(kind='Body',feature_id='block'),dict(kind='Body',feature_id='tool')])
 ],expected_volume_mm3=5000,volume_tolerance_percent=.01),
 'intersect_blocks':draft('intersect_blocks',[
    sketch('base',[rect(20,20)]),boss('block','base',10),
    sketch('tool_profile',[rect(20,20,x=10)]),boss('tool','tool_profile',10,merge=False),
    feature('intersection','Combine',boolean_mode='Intersect',selections=[dict(kind='Body',feature_id='block'),dict(kind='Body',feature_id='tool')])
 ],expected_volume_mm3=2000,volume_tolerance_percent=.01),
 'circular_holes':draft('circular_holes',[
    sketch('base',[circle(60)]),boss('plate','base',10),
    feature('hole','Hole',diameter_mm=5,hole_centers=[dict(xmm=20,ymm=0)]),
    feature('axis','ReferenceAxis',axis_start_mm=dict(x=0,y=0,z=0),axis_end_mm=dict(x=0,y=0,z=20)),
    feature('pattern','CircularPattern',count=4,angle_degrees=360,selections=[dict(kind='Axis',feature_id='axis',selection_mark=1),dict(kind='Feature',feature_id='hole',selection_mark=4)])
 ],expected_volume_mm3=(900-25)*math.pi*10,volume_tolerance_percent=.01),
 'mirror_hole':draft('mirror_hole',[
    sketch('base',[rect(60,40)]),boss('plate','base',10),
    feature('hole','Hole',diameter_mm=6,hole_centers=[dict(xmm=20,ymm=0)]),
    feature('mirror_plane','ReferencePlane',frame=dict(normal=dict(x=1,y=0,z=0),x_direction=dict(x=0,y=1,z=0))),
    feature('mirror','Mirror',selections=[dict(kind='Feature',feature_id='hole',selection_mark=1),dict(kind='Plane',feature_id='mirror_plane',selection_mark=2)])
 ],expected_volume_mm3=24000-2*math.pi*9*10,volume_tolerance_percent=.01),
 'surface_only':draft('surface_only',[
    sketch('outline',[rect(40,30)]),feature('surface','SurfacePlanar',sketch_id='outline')
 ],expected_solid_body_count=0,expected_surface_body_count=1,expected_bounding_box_mm=dict(x=40,y=30,z=0)),
 'shell_box':draft('shell_box',[
    sketch('base',[rect(40,30)]),boss('block','base',20),
    feature('shell','Shell',thickness_mm=2,selections=[dict(kind='Face',feature_id='block',geometry='Plane',position_mm=dict(x=0,y=0,z=20))])
 ],expected_volume_mm3=40*30*20-36*26*18,volume_tolerance_percent=.01),
 'loft_cone':draft('loft_cone',[
    sketch('bottom',[circle(20)]),
    sketch('top',[circle(10)],frame=dict(origin_mm=dict(x=0,y=0,z=30))),
    feature('loft','LoftBoss',profile_ids=['bottom','top'])
 ],expected_volume_mm3=math.pi*30/3*(100+50+25),volume_tolerance_percent=.1),
 'sweep_tube':draft('sweep_tube',[
    sketch('profile',[circle(10),circle(6,'Inner')]),
    sketch('path',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=0,ymm=0),end=dict(xmm=0,ymm=40))])],plane='Top'),
    feature('sweep','SweepBoss',sketch_id='profile',path_sketch_id='path')
 ],expected_volume_mm3=math.pi*16*40,volume_tolerance_percent=.01),
 'combine_blocks':draft('combine_blocks',[
    sketch('first',[rect(20,20)]),boss('block_a','first',10),
    sketch('second',[rect(20,20,x=10)]),boss('block_b','second',10,merge=False),
    feature('union','Combine',boolean_mode='Union',selections=[dict(kind='Body',feature_id='block_a'),dict(kind='Body',feature_id='block_b')])
 ],expected_volume_mm3=6000,volume_tolerance_percent=.01),
 'move_body':draft('move_body',[
    sketch('base',[rect(20,10)]),boss('block','base',5),
    feature('translated','MoveBody',translation_mm=dict(x=30,y=10,z=0),selections=[dict(kind='Body',feature_id='block')])
 ],expected_volume_mm3=1000,volume_tolerance_percent=.01),
 'linear_holes':draft('linear_holes',[
    sketch('base',[rect(80,30)]),boss('block','base',10),
    sketch('hole_profile',[circle(5,x=-25)]),dict(type='ExtrudeCut',id='hole',name='hole',sketch_id='hole_profile',depth_mm=20,end_condition='ThroughAll'),
    feature('pattern_axis','ReferenceAxis',axis_start_mm=dict(x=0,y=0,z=0),axis_end_mm=dict(x=10,y=0,z=0)),
    feature('holes','LinearPattern',count=3,spacing_mm=20,selections=[dict(kind='Axis',feature_id='pattern_axis',selection_mark=1),dict(kind='Feature',feature_id='hole',selection_mark=4)])
 ],expected_volume_mm3=24000-3*math.pi*2.5**2*10,volume_tolerance_percent=.01)
})

prior=list((Path(__file__).resolve().parents[1]/'artifacts').glob('*/box_fillet.SLDPRT'))
if prior:
    cases['edit_height']=draft('edit_height',[
        feature('change_depth','SetDimension',dimension_name='D1@block',dimension_value=20)
    ],source_model_path=str(sorted(prior)[-1]),expected_volume_mm3=(1200-4*(4-math.pi))*20,volume_tolerance_percent=.01)

cases.update({
 'slot_plate':draft('slot_plate',[
    sketch('slot',[dict(type='Slot',points=[dict(xmm=-15,ymm=0),dict(xmm=15,ymm=0)],width_mm=10)]),boss('plate','slot',5)
 ],expected_volume_mm3=(300+math.pi*25)*5,volume_tolerance_percent=.01),
 'driven_circle':draft('driven_circle',[
    sketch('profile',[circle(10)],dimensions=[dict(name='Diameter',kind='Diameter',value=20,entities=[dict(primitive_index=0,segment_index=0)],label_position=dict(xmm=20,ymm=20))]),
    boss('cylinder','profile',10)
 ],expected_volume_mm3=1000*math.pi,volume_tolerance_percent=.01),
 'counterbores':draft('counterbores',[
    sketch('base',[rect(60,40)]),boss('plate','base',10),
    feature('mounting_holes','Hole',hole_kind='Counterbore',diameter_mm=6,counterbore_diameter_mm=10,counterbore_depth_mm=3,
        hole_centers=[dict(xmm=-20,ymm=0),dict(xmm=20,ymm=0)])
 ],expected_volume_mm3=24000-2*math.pi*(9*10+16*3),volume_tolerance_percent=.01),
 'countersink':draft('countersink',[
    sketch('base',[rect(40,30)]),boss('plate','base',10),
    feature('mounting_hole','Hole',hole_kind='Countersink',diameter_mm=6,countersink_diameter_mm=12,countersink_angle_degrees=90,
        hole_centers=[dict(xmm=0,ymm=0)])
 ],expected_volume_mm3=12000-math.pi*(9*10+36),volume_tolerance_percent=.1),
 'tapped_hole':draft('tapped_hole',[
    sketch('base',[rect(40,30)]),boss('plate','base',10),
    feature('m8_hole','Hole',hole_kind='Tapped',diameter_mm=6.8,thread_major_diameter_mm=8,thread_designation='M8 x 1.25',depth_mm=10,
        hole_centers=[dict(xmm=0,ymm=0)])
 ],expected_volume_mm3=12000-math.pi*3.4**2*10,volume_tolerance_percent=.01),
 'thin_wall':draft('thin_wall',[
    sketch('line',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=-20,ymm=0),end=dict(xmm=20,ymm=0))])]),
    feature('wall','ThinExtrude',sketch_id='line',thickness_mm=2,depth_mm=10)
 ],expected_volume_mm3=800,volume_tolerance_percent=.01),
 'sheet_base':draft('sheet_base',[
    sketch('outline',[rect(60,40)]),feature('sheet','SheetMetalBase',sketch_id='outline',thickness_mm=2,radius_mm=2),
    feature('flatten','Flatten',flattened=True)
 ],expected_volume_mm3=4800,volume_tolerance_percent=.01),
 'surface_thicken':draft('surface_thicken',[
    sketch('line',[dict(type='OpenCurve',curves=[dict(type='Line',start=dict(xmm=-20,ymm=0),end=dict(xmm=20,ymm=0))])]),
    feature('surface','SurfaceExtrude',sketch_id='line',depth_mm=20),
    feature('thicken','Thicken',thickness_mm=2,selections=[dict(kind='Face',feature_id='surface')])
 ],expected_volume_mm3=1600,volume_tolerance_percent=.01)
})

cases.update(workflow_cases)
cases['polygon_on_plane'] = draft('polygon_on_plane',[
    sketch('section',[dict(type='Polygon',points=[dict(xmm=-10,ymm=0),dict(xmm=10,ymm=0),dict(xmm=5,ymm=30),dict(xmm=-5,ymm=30)])],
           frame=dict(normal=dict(x=0,y=-1,z=0),x_direction=dict(x=1,y=0,z=0))),
    boss('prism','section',8)
],expected_volume_mm3=3600,volume_tolerance_percent=.01,expected_bounding_box_mm=dict(x=20,y=8,z=30),expected_center_of_mass_mm=dict(x=0,y=-4,z=40/3))
