using CadModeling.Core;
using CadModeling.Ir;

var count=0;
void Check(bool condition,string name) {if(!condition)throw new Exception(name);count++;Console.WriteLine("PASS "+name);}
var c=new CylinderGroupCheck{Id="hole",SourceLiteral="Diameter 10, axis x=20, depth 10",DiameterMm=10,LengthMm=10,AxisStartsMm=[new(20,0,0)]};
var spec=new ModelVerificationSpec{CylinderGroups=[c]};
var wall=new MeasuredCylinder(new(20,0,0),new(20,0,10),new(0,0,1),5,100*Math.PI,true,"hole");
bool Pass(params MeasuredCylinder[] walls)=>ModelVerification.Evaluate(spec,walls,new Dictionary<string,double>(),null).Passed;
Check(Pass(wall),"exact cylinder passes");
Check(Pass(wall with {AxisStartMm=wall.AxisEndMm,AxisEndMm=wall.AxisStartMm,Direction=new(0,0,-1)}),"surface parameter direction does not reverse hole intent");
Check(!Pass(),"missing hole rejected");
Check(!Pass(wall with {RadiusMm=4}),"wrong diameter rejected");
Check(!Pass(wall with {AxisStartMm=new(-20,0,0),AxisEndMm=new(-20,0,10)}),"mirrored position rejected");
Check(!Pass(wall with {AxisStartMm=new(20,0,1),AxisEndMm=new(20,0,11)}),"correct length at wrong axial station rejected");
Check(!Pass(wall with {AxisEndMm=new(20,0,8)}),"wrong depth rejected");
Check(!Pass(wall with {Interior=false}),"boss cannot satisfy a hole requirement");
Check(!Pass(wall with {AreaMm2=50*Math.PI}),"half hole is not a complete hole");
Check(!Pass(wall,wall with {AxisStartMm=new(30,0,0),AxisEndMm=new(30,0,10)}),"extra hole rejected");
Check(Pass(wall with {AreaMm2=50*Math.PI},wall with {AreaMm2=50*Math.PI}),"seam split cylinder counted once");
Check(Pass(wall with {AxisEndMm=new(20,0,5),AreaMm2=50*Math.PI},wall with {AxisStartMm=new(20,0,5),AreaMm2=50*Math.PI}),"axially split contiguous wall counted once");
Check(!Pass(wall with {AxisEndMm=new(20,0,4),AreaMm2=40*Math.PI},wall with {AxisStartMm=new(20,0,6),AreaMm2=40*Math.PI}),"coaxial blind holes with a material gap not merged");
Check(!Pass(wall with {AreaMm2=double.NaN}),"invalid native measurement is unverifiable");
var diagonal=ModelVerification.Unit(new(1,1,1));
var start=new Vector3(10,20,30);
var tilted=c with {AxisStartsMm=[start],Direction=diagonal};
var tiltedWall=wall with {AxisStartMm=start,AxisEndMm=ModelVerification.Add(start,ModelVerification.Scale(diagonal,10)),Direction=diagonal};
Check(ModelVerification.Evaluate(new(){CylinderGroups=[tilted]},[tiltedWall],new Dictionary<string,double>(),null).Passed,"arbitrary axis direction measured in model coordinates");
Check(ModelVerification.Validate(new(){CylinderGroups=[c with {AxisStartsMm=[new(0,0,0),new(0,0,0)]}]},null).Any(),"duplicate expected axes rejected");
Check(ModelVerification.Validate(new(){CylinderGroups=[c with {Direction=new(0,0,0)}]},null).Any(),"zero direction rejected");
Check(ModelVerification.Validate(new(){CylinderGroups=[c with {ToleranceMm=double.PositiveInfinity}]},null).Any(),"infinite tolerance rejected");
Check(ModelVerification.Validate(new(){CylinderGroups=[c,c]},null).Any(),"duplicate check ID rejected");
var native=new ModelVerificationSpec{NativeDimensions=[new(){Id="angle",SourceLiteral="90 degrees",DimensionName="D1@revolve",Unit=DrawingValueUnit.Degree,Value=90,Tolerance=.01}]};
Check(ModelVerification.Evaluate(native,[],new Dictionary<string,double>{{"D1@revolve",Math.PI/2}},null).Passed,"native radians converted to degrees");
Check(!ModelVerification.Evaluate(native,[],new Dictionary<string,double>(),null).Passed,"absent native dimension unverifiable");
var sample=new SurfaceSampleCheck{Id="local",SourceLiteral="Hole wall at (5,0,5)",SurfaceKind=LocalSurfaceKind.Cylinder,PointsMm=[new(5,0,5)],OutwardNormals=[new(-1,0,0)],DiameterMm=10};
var local=new ModelVerificationSpec{SurfaceSamples=[sample]};
var face=new LocalFaceMeasurement(new(5,0,5),new(-1,0,0),LocalSurfaceKind.Cylinder,10);
ModelVerificationResult Local(ModelVerificationSpec checks, LocalPointMeasurement measured)=>ModelVerification.Evaluate(checks,[],new Dictionary<string,double>(),null,new Dictionary<string,IReadOnlyList<LocalPointMeasurement>>{{"local",new[]{measured}}});
Check(!ModelVerification.Validate(local,null).Any(),"valid local cylinder contract");
Check(Local(local,new([face],true)).Passed,"actual partial wall sample passes");
Check(!Local(local,new([face with {ClosestPointMm=new(7,0,5)}],true)).Passed,"trimmed-away analytic extension rejected");
Check(!Local(local,new([face with {OutwardNormal=new(1,0,0)}],true)).Passed,"opposite material side rejected");
Check(!Local(local,new([face with {DiameterMm=9}],true)).Passed,"same point wrong cylinder radius rejected");
Check(!Local(local,new([face with {Kind=LocalSurfaceKind.Plane}],true)).Passed,"wrong surface kind rejected");
Check(!Local(local,new([face],false,"COM failed")).Passed,"partial face inventory fails closed");
Check(!Local(local,new([],true)).Passed,"empty solid inventory fails closed");
Check(!ModelVerification.Evaluate(local,[],new Dictionary<string,double>(),null).Passed,"missing local measurements fail closed");
Check(!Local(local,new([face with {OutwardNormal=new(double.NaN,0,0)}],true)).Passed,"invalid measured normal fails closed");
var cone=local with {SurfaceSamples=[sample with {SurfaceKind=LocalSurfaceKind.Cone,DiameterMm=null,ConeHalfAngleDegrees=59}]};
Check(Local(cone,new([face with {Kind=LocalSurfaceKind.Cone,DiameterMm=null,ConeHalfAngleDegrees=59}],true)).Passed,"cone half angle accepted");
Check(!Local(cone,new([face with {Kind=LocalSurfaceKind.Cone,DiameterMm=null,ConeHalfAngleDegrees=45}],true)).Passed,"wrong drill tip angle rejected");
var gap=new ModelVerificationSpec{BoundaryClearances=[new(){Id="local",SourceLiteral="No wall within 2 mm",PointsMm=[new(5,0,5)],MinimumDistanceMm=2}]};
Check(Local(gap,new([face with {ClosestPointMm=new(8,0,5)}],true)).Passed,"boundary clearance passes");
Check(!Local(gap,new([face],true)).Passed,"uncut wall violates clearance");
Check(!Local(gap,new([face with {ClosestPointMm=new(8,0,5)}],false)).Passed,"unread face cannot certify clearance");
Check(ModelVerification.Validate(local with {SurfaceSamples=[sample with {OutwardNormals=[]}]},null).Any(),"missing normals rejected");
Check(ModelVerification.Validate(local with {SurfaceSamples=[sample with {SurfaceKind=LocalSurfaceKind.Plane}]},null).Any(),"irrelevant cylinder parameter rejected");
Check(ModelVerification.Validate(gap with {BoundaryClearances=[gap.BoundaryClearances[0] with {MinimumDistanceMm=.001}]},null).Any(),"vacuous clearance tolerance rejected");
var angleFact=new DrawingDimensionFact{Id="source_angle",OperationId="sink",ParameterPath="feature.countersink_angle_degrees",Value=118,Unit=DrawingValueUnit.Degree,SourceLiteral="118 degrees"};
var angleContext=new DrawingPlanContext{SourcePath="unused-in-validator",Dimensions=[angleFact]};
var boundCone=cone with {SurfaceSamples=[cone.SurfaceSamples[0] with {SourceDimensionIds=["source_angle"]}],Bindings=[new("source_angle","local","cone_included_angle_degrees")]};
Check(!ModelVerification.Validate(boundCone,angleContext).Any(),"included source angle binds to twice measured half angle");
Check(ModelVerification.Validate(boundCone,angleContext with {Dimensions=[angleFact with {Value=90}]}).Any(),"included source angle mismatch rejected");
Check(ModelVerification.Validate(boundCone,angleContext with {Dimensions=[angleFact with {Unit=DrawingValueUnit.Millimeter}]}).Any(),"cone angle cannot bind a length");
Check(ModelVerification.Validate(local with {SurfaceSamples=[sample with {PointsMm=Enumerable.Repeat(new Vector3(5,0,5),513).ToArray(),OutwardNormals=Enumerable.Repeat(new Vector3(-1,0,0),513).ToArray()}]},null).Any(),"unbounded local workload rejected");
var areaSpec=local with {SurfaceSamples=[sample with {ExpectedAreaMm2=50*Math.PI}]};
var areaFace=face with {FaceIndex=7,AreaMm2=50*Math.PI};
Check(Local(areaSpec,new([areaFace],true)).Passed,"partial wall area matches analytic source");
Check(!Local(areaSpec,new([areaFace with {AreaMm2=40*Math.PI}],true)).Passed,"correct sample with missing remote area rejected");
Check(!Local(areaSpec,new([areaFace with {AreaMm2=60*Math.PI}],true)).Passed,"extra wall area rejected");
Check(!Local(areaSpec,new([face],true)).Passed,"missing face area fails closed");
var repeated=areaSpec with {SurfaceSamples=[areaSpec.SurfaceSamples[0] with {PointsMm=[new(5,0,5),new(5,0,5)],OutwardNormals=[new(-1,0,0),new(-1,0,0)]}]};
Check(ModelVerification.Evaluate(repeated,[],new Dictionary<string,double>(),null,new Dictionary<string,IReadOnlyList<LocalPointMeasurement>>{{"local",new[]{new LocalPointMeasurement([areaFace],true),new LocalPointMeasurement([areaFace],true)}}}).Passed,"same face sampled twice is counted once");
Check(!Local(areaSpec,new([areaFace with {AreaErrorMm2=.2}],true)).Passed,"area uncertainty cannot exceed acceptance tolerance");
Check(Local(areaSpec,new([areaFace with {AreaErrorMm2=.01}],true)).Passed,"converged area retains uncertainty margin");
Check(!Local(areaSpec,new([areaFace with {AreaMm2=50*Math.PI+.095,AreaErrorMm2=.01}],true)).Passed,"near-threshold area remains unverifiable");
Check(!Local(areaSpec,new([areaFace with {AreaErrorMm2=double.NaN}],true)).Passed,"invalid numerical uncertainty fails closed");
Console.WriteLine($"{count} focused core checks passed.");

